backend/blog/entry/models.py
from datetime import datetime
from flask import Markup, current_app
from markdown import markdown
from markdown.extensions.codehilite import CodeHiliteExtension
from markdown.extensions.extra import ExtraExtension
from micawber import parse_html, bootstrap_basic
from micawber.cache import Cache as OEmbedCache
from sqlalchemy.sql.expression import false
from sqlalchemy.ext.hybrid import hybrid_property
import re

from blog.entry.images import handle_image
from blog.orm import db

# Configure micawber with the default OEmbed providers (YouTube, Flickr, etc).
# We'll use a simple in-memory cache so that multiple requests for the same
# video don't require multiple network requests.
oembed_providers = bootstrap_basic(OEmbedCache())


class Entry(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    author = db.relationship('User')
    title = db.Column(db.String(255), unique=True)
    slug = db.Column(db.String(255), unique=True)
    tagline = db.Column(db.String(5000))
    content = db.Column(db.String(50000))
    published = db.Column(db.Boolean())
    timestamp = db.Column(db.DateTime(), default=datetime.now)
    _image = db.Column('image', db.String(255))

    @hybrid_property
    def image(self):
        return self._image

    @image.setter
    def image(self, value):
        self._image = handle_image(value) if hasattr(value, 'data') else self._image

    @classmethod
    def create(cls, title, tagline, content, published=False, image=None):
        slug = re.sub('[^\w]+', '-', title.lower())
        e = Entry(title=title, tagline=tagline, content=content, published=published, slug=slug, image=image)
        db.session.add(e)
        db.session.commit()
        return e

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def public(cls):
        return Entry.query.filter(Entry.published)

    @classmethod
    def drafts(cls):
        return Entry.query.filter(Entry.published == false())

    @property
    def html_content(self):
        hilite = CodeHiliteExtension(linenums=False, css_class='highlight')
        extras = ExtraExtension()
        markdown_content = markdown(self.content, extensions=[hilite, extras])
        oembed_content = parse_html(
            markdown_content,
            oembed_providers,
            urlize_all=True,
            maxwidth=current_app.config['SITE_WIDTH'])
        return Markup(oembed_content)


class Comment(db.Model):
    id = db.Column('id', db.Integer(), primary_key=True)
    user_id = db.Column('user_id', db.Integer(), db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User')
    post_id = db.Column('post_id', db.Integer(), db.ForeignKey('entry.id'), nullable=False)
    post = db.relationship('Entry')
    text = db.Column('text', db.Text(), nullable=True)
    timestamp = db.Column('timestamp', db.DateTime(), nullable=False)

backend/blog/security/models.py
from flask_security import Security, SQLAlchemyUserDatastore, UserMixin, RoleMixin

from blog.orm import db

roles_users = db.Table(
    'roles_users',
    db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
    db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
)


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    alias = db.Column(db.String(255), unique=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime())
    roles = db.relationship('Role', secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))


# Setup Flask-Security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app=None, datastore=user_datastore)

backend/blog/status_day/models.py
from blog.orm import db


class StatusDay(db.Model):
    date = db.Column('date', db.DateTime(), primary_key=True)
    status = db.Column('status', db.String(255))

backend/blog/entry/forms.py
from flask_wtf import Form
from wtforms import StringField, BooleanField, FileField, TextAreaField

class CreateForm(Form):
    title = StringField('title')
    tagline = StringField('tagline')
    image = FileField('image')
    content = TextAreaField('content')
    published = BooleanField('published')

class ImageForm(Form):
    image = FileField('image')

class UpdateForm(Form):
    image = FileField('image')
    entry = StringField('entry')

backend/blog/__init__.py
__author__ = 'pbecotte'

backend/blog/entry/__init__.py
from .models import Entry
from .views import entry

backend/blog/entry/views.py
from flask import Blueprint, current_app, request, flash, render_template, redirect, url_for
from flask.ext.security import login_required, current_user
from .forms import CreateForm, ImageForm
from .images import handle_image
from .models import Entry
from blog.utils import object_list, get_object_or_404

entry = Blueprint('entry', __name__)


@entry.route('/')
def index():
    query, search_query = index_func()
    return object_list('index.html', query, search=search_query)


def index_func():
    search_query = request.args.get('q')
    if search_query:
        query = Entry.search(search_query)
    else:
        query = Entry.public().order_by(Entry.timestamp.desc())
    return query, search_query


@entry.route('/drafts/')
@login_required
def drafts():
    query = Entry.drafts().order_by(Entry.timestamp.desc())
    return object_list('index.html', query)


@entry.route('/<slug>/')
def detail(slug):
    if current_user.is_authenticated():
        query = Entry.query
    else:
        query = Entry.public()
    entry = get_object_or_404(query, Entry.slug == slug)
    image_url = '{bucket}{path}/{filename}'.format(
        bucket=current_app.config['S3_LOCATION'],
        path=current_app.config['S3_UPLOAD_DIRECTORY'],
        filename=entry.image) if entry.image else ''
    return render_template('detail.html', entry=entry, image=image_url)


@entry.route('/create/', methods=['GET', 'POST'])
@login_required
def create():
    form = CreateForm()
    if request.method == 'POST':
        if form.title and form.content:
            image = form.image if form.image else None

            entry = Entry.create(
                title=form.title.data,
                tagline=form.tagline.data,
                content=form.content.data,
                published=form.published.data,
                image=image
            )
            flash('Entry created successfully.', 'success')
            if entry.published:
                return redirect(url_for('entry.detail', slug=entry.slug))
            else:
                return redirect(url_for('entry.edit', slug=entry.slug))
        else:
            flash('Title and Content are required.', 'danger')

    image_form = ImageForm()
    return render_template('create.html', form=form, image_form=image_form)


@entry.route('/<slug>/edit/', methods=['GET', 'POST'])
@login_required
def edit(slug):
    entry = get_object_or_404(Entry.query, Entry.slug == slug)
    if request.method == 'POST':
        form = CreateForm()
        if form.title and form.content:
            entry.title = form.title.data
            entry.tagline = form.tagline.data
            entry.image = handle_image(form.image) if form.image.data else entry.image
            entry.content = form.content.data
            entry.published = form.published.data
            entry.save()

            flash('Entry saved successfully.', 'success')
            if entry.published:
                return redirect(url_for('entry.detail', slug=entry.slug))
            else:
                return redirect(url_for('entry.edit', slug=entry.slug))
        else:
            flash('Title and Content are required.', 'danger')

    form = CreateForm(obj=entry)
    image_form = ImageForm()
    return render_template('edit.html', entry=entry, form=form, image_form=image_form)


@entry.route('/upload_image/', methods=['POST'])
@login_required
def upload_image():
    form = ImageForm()
    image_name = handle_image(form.image) if form.image else ''
    return '{bucket}{path}/{filename}'.format(
        bucket=current_app.config['S3_LOCATION'],
        path=current_app.config['S3_UPLOAD_DIRECTORY'],
        filename=image_name)

backend/blog/security/__init__.py
from .models import security, user_datastore

backend/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title{% block title %}>Paul Becotte{% endblock %}</title>
    <!-- Google Analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-66388176-1', 'auto');
      ga('send', 'pageview');

    </script>


    <!-- Bootstrap Core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/blog.min.css') }}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extra_head %}{% endblock %}
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top" style="background-color:black; opacity:0.7;">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Paul Becotte</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    {% if current_user.is_authenticated() %}
                      <li><a href="{{ url_for('entry.drafts') }}">Drafts</a></li>
                      <li><a href="{{ url_for('entry.create') }}">Create Entry</a></li>
                      <li><a href="{{ url_for('security.logout') }}">Log out</a></li>
                    {% else %}
                      <li><a href="{{ url_for('security.login') }}">Log in</a></li>
                    {% endif %}
                    {% block extra_header %}{% endblock %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    {% block page_header %}
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('{% block header_image %}{{ url_for('static', filename='img/home-bg.jpg') }}{% endblock %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                    <div style="background-color:black; opacity:0.7;">
                        <h1 >{%  block content_title %}Paul Becotte {% endblock %}</h1>
                        <hr class="small">
                        <span class="subheading">{% block tagline %}A Python/Devops guy's personal blog{% endblock %}</span>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% endblock %}

    <!-- Main Content -->
    <div class="container">
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{ category }} alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <p>{{ message }}</p>
        </div>
      {% endfor %}
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              {% block content %}{% endblock %}
          </div>
      </div>
    </div>
    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://twitter.com/paulbecotte">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/paul.becotte.3">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/pbecotte">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Paul Becotte 2015-2016</p>
                    <p class="copyright text-muted">
                        All code samples are released under the
                        <a href="http://creativecommons.org/licenses/by-sa/3.0/">
                            Creative Commons Attribution/Share-Alike License.
                        </a>
                    </p>
                    <p class="copyright text-muted">Header courtesy of <a href="http://www.freewebheaders.com">Free Web Headers</a></p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{{ url_for('static', filename='js/jquery-1.11.0.min.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

    <!-- Custom Theme JavaScript -->
    {% block extra_scripts %}{% endblock %}
</body>

</html>

backend/blog/templates/create.html
{% extends "base.html" %}

{% block title %}Create entry{% endblock %}

{% block content_title %}Create entry{% endblock %}

{% block content %}
<form action="{{ url_for('entry.create') }}" class="form-horizontal" method="post" enctype="multipart/form-data">
{{ form.csrf_token }}
    <div class="form-group">
        {{ form.title.label(class="col-sm-2 control-label")}}
        <div class="col-sm-10">
            {{ form.title(class="form-control") }}
        </div>
    </div>
    <div class="form-group">
        {{ form.tagline.label(class="col-sm-2 control-label")}}
        <div class="col-sm-10">
            {{ form.tagline(class="form-control") }}
        </div>
    </div>
    <div class="form-group">
        {{ form.image.label(class="col-sm-2 control-label") }}
        <div class="col-sm-10">
            {{ form.image }}
        </div>
    </div>
    <div class="form-group">
        {{ form.content.label(class="col-sm-2 control-label") }}
        <div class="col-sm-10">
            {{ form.content(style="height: 300px;", class="form-control") }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            {{ form.published.label }}  {{ form.published }}
        </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-primary" type="submit">Create</button>
        <a class="btn btn-default" href="{{ url_for('entry.index') }}">Cancel</a>
      </div>
    </div>
</form>

<form action="{{ url_for('entry.upload_image') }}" id="uploadForm" enctype="multipart/form-data">
    <div class="form-group">
        {{ form.image.label(class="col-sm-2 control-label") }}
        <div class="col-sm-10">
            {{ form.image }}
        </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-primary" type="submit">Upload</button>
        <div id="result"></div>
      </div>
    </div>
</form>
<!-- the filename from the upload will be rendered inside this div -->
<div id="result"></div>
{% endblock %}

{% block extra_scripts %}
<script>
// Attach a submit handler to the form
$( "#uploadForm" ).submit(function( event ) {

    var formData = new FormData($( this )[0]);
    var url = $( this ).attr( "action" )

    $.ajax({
        url: url,
        type: 'POST',
        data: formData,
        async: false,
        success: function (data) {
            $( "#result" ).empty().append( data );
        },
        cache: false,
        contentType: false,
        processData: false
    });

    return false;
});
</script>
{% endblock %}

backend/blog/templates/detail.html
{% extends "base.html" %}

{% block title %}{{ entry.title }}{% endblock %}



{% block extra_header %}
  {% if current_user.is_authenticated() %}
    <li><a href="{{ url_for('entry.edit', slug=entry.slug) }}">Edit entry</a></li>
  {% endif %}
{% endblock %}

{% block header_image %}{{ image }}{% endblock %}
{% block content_title %}{{ entry.title }}{% endblock %}
{% block tagline %}{{ entry.tagline }}{% endblock %}

{% block content %}
  <p>Created {{ entry.timestamp.strftime('%m/%d/%Y at %l:%M%p') }}</p>
  {{ entry.html_content }}
{% endblock %}

backend/blog/templates/edit.html
{% extends "base.html" %}

{% block title %}Edit entry{% endblock %}

{% block content_title %}Edit entry{% endblock %}

{% block content %}
<form action="{{ url_for('entry.edit', slug=entry.slug) }}" class="form-horizontal" method="post" enctype="multipart/form-data">
{{ form.csrf_token }}
    <div class="form-group">
        {{ form.title.label(class="col-sm-2 control-label")}}
        <div class="col-sm-10">
            {{ form.title(class="form-control") }}
        </div>
    </div>
    <div class="form-group">
        {{ form.tagline.label(class="col-sm-2 control-label")}}
        <div class="col-sm-10">
            {{ form.tagline(class="form-control") }}
        </div>
    </div>
    <div class="form-group">
        {{ form.image.label(class="col-sm-2 control-label") }}
        <div class="col-sm-10">
            {{ form.image }}
        </div>
    </div>
    <div class="form-group">
        {{ form.content.label(class="col-sm-2 control-label") }}
        <div class="col-sm-10">
            {{ form.content(style="height: 300px;", class="form-control") }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            {{ form.published.label }}  {{ form.published }}
        </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-primary" type="submit">Update</button>
        <a class="btn btn-default" href="{{ url_for('entry.index') }}">Cancel</a>
      </div>
    </div>
</form>
<form action="{{ url_for('entry.upload_image') }}" id="uploadForm" enctype="multipart/form-data">
    <div class="form-group">
        {{ form.image.label(class="col-sm-2 control-label") }}
        <div class="col-sm-10">
            {{ form.image }}
        </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-primary" type="submit">Upload</button>
        <div id="result"></div>
      </div>
    </div>
</form>
<!-- the filename from the upload will be rendered inside this div -->
<div id="result"></div>
{% endblock %}

{% block extra_scripts %}
<script>
// Attach a submit handler to the form
$( "#uploadForm" ).submit(function( event ) {

    var formData = new FormData($( this )[0]);
    var url = $( this ).attr( "action" )

    $.ajax({
        url: url,
        type: 'POST',
        data: formData,
        async: false,
        success: function (data) {
            $( "#result" ).empty().append( data );
        },
        cache: false,
        contentType: false,
        processData: false
    });

    return false;
});
</script>
{% endblock %}

backend/blog/templates/error.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content_title %}{% endblock %}

{% block extra_header %}{% endblock %}

{% block content %}
  {{ message }}
{% endblock %}

backend/blog/templates/includes/pagination.html
{% if pagination.get_page_count() > 1 %}
<ul class="pager">
  {% if pagination.get_page() > 1 %}
    <li class="previous"><a href="./?{{ request.args|clean_querystring('page', page=pagination.get_page() - 1) }}">&laquo; Previous {{ pagination.get_page() - 1 }} / {{ pagination.get_page_count() }}</a></li>
  {% else %}
    <li class="previous disabled"><a href="#">&laquo; Previous</a></li>
  {% endif %}
  {% if pagination.get_page_count() > pagination.get_page() %}
    <li class="next"><a href="./?{{ request.args|clean_querystring('page', page=pagination.get_page() + 1) }}">Next {{ pagination.get_page() + 1 }} / {{ pagination.get_page_count() }} &raquo;</a></li>
  {% else %}
    <li class="next disabled"><a href="#">Next &raquo;</a></li>
  {% endif %}
</ul>
{% endif %}

backend/blog/templates/index.html
{% extends "base.html" %}

{% block title %}Blog entries{% endblock %}

{% block content_title %}{% if search %}Search "{{ search }}"{% else %}Paul Becotte{% endif %}{% endblock %}

{% block content %}
  {% for entry in object_list %}
    {% if search %}
      {% set entry = entry.entry %}
    {% endif %}
    <div class="post-preview">
      <a href="{% if entry.published %}{{ url_for('entry.detail', slug=entry.slug) }}{% else %}{{ url_for('entry.edit', slug=entry.slug) }}{% endif %}">
        <h2 class="post-title">
            {{ entry.title }}
        </h2>
        <h3 class="post-subtitle">
          {{ entry.tagline }}
        </h3>
      </a>
    <p class="post-meta">
        Created {{ entry.timestamp.strftime('%m/%d/%Y at %l:%M%p') }}
    </p>
    </div>
    <hr>
  {% endfor %}
  {% include "includes/pagination.html" %}
{% endblock %}

backend/blog/templates/security/login_user.html
{% extends "base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% block content_title %}Login{% endblock %}
{% block content %}
<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email) }}
  {{ render_field_with_errors(login_user_form.password) }}
  {{ render_field_with_errors(login_user_form.remember) }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit) }}
</form>
{% include "security/_menu.html" %}
{% endblock %}